---
cors:
  enabled: true
  allowed_origins:
    - http://http://auxquimia.desa.izertis.com
    - https://http://auxquimia.desa.izertis.com
    - https://jwt.io
cache:
  remote:
    enabled: false
  redis:
    connection_string: "auxquimia-redis-master.auxquimia.svc.cluster.local,password=X0AkImZzHb,connectTimeout=2000,syncTimeout=2000,keepalive=20"
identity_server:
  redis:
    enabled: true
    connection_string: "auxquimia-redis-master.auxquimia.svc.cluster.local,password=X0AkImZzHb,connectTimeout=2000,syncTimeout=2000,keepalive=20"
  use_developer_credential: true
database:
  app:
    connection_string: server=172.16.0.4;port=5433;database=auxquimia
      ;user id=auxquimia;password=87ReaPEr:%;
opcua:
  client:
    node-file: Servipesainterface.xml
ftp:
  server: localhost:21
  filepath_read: working_order.csv
  filepath_write: working_order_write.csv
  username: user
  password: 1234
kafka:
  server: localhost:9092
email_config:
  email_server_out: "smtp.gmail.com"
  email_require_ssl_out: true
  email_port_out: 587
  email_address: "izertisdotnet@gmail.com"
  email_pass: "net@izertis"
  url: https://auxquimia.desa.izertis.com/password